 // This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
 // <auto-generated/> 
namespace MyProject.Roles.Dto
{
    public class GetRolesInput
    {
        public string Permission { get; set; }
    }
}
