 // This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
 // <auto-generated/> 
using Abp.Application.Services;
using Abp.Application.Services.Dto;
using MyProject.DanhMuc.Demo.Dtos;
using MyProject.Data;
using System.Threading.Tasks;

namespace MyProject.DanhMuc.Demo
{
    public interface IDemoAppService 
    {
        Task<PagedResultDto<DemoForView>> GetAllAsync(DemoGetAllInputDto input);
        Task<int> CreateOrEdit(DemoCreateInput input);
        Task<DemoCreateInput> GetForEditAsync(EntityDto input);
        Task Delete(EntityDto input);
        Task<FileDto> ExportToExcel(DemoGetAllInputDto input);
        Task<string> ImportFileExcel(string FilePath);
        Task<FileDto> DownloadFileMau();
    }
}
