 // This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
 // <auto-generated/> 
using System;
using System.Collections.Generic;
using System.Text;

namespace MyProject.DanhMuc.Demo.Dtos
{
    public class DemoForView
    {
        public DemoDto Demo { get; set; }
        public string TrangThai { get; set; }
        public string TrangThaiDuyet { get; set; }

    }
}
