 // This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
 // <auto-generated/> 
using Abp.Application.Services.Dto;

namespace MyProject.DanhMuc.Demo.Dtos
{
    public class DemoGetAllInputDto : PagedResultRequestDto
    {
        public string Keyword { get; set; }
    }
}
