// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using Abp.Application.Services.Dto;
using System;
using System.Collections.Generic;

namespace MyProject.Users.Dto
{
    //custom PagedResultRequestDto
    public class PagedUserResultRequestDto : PagedAndSortedResultRequestDto
    {
        public string Keyword { get; set; }
        public bool? IsActive { get; set; }
        public List<int> ToChucIdList { get; set; }

        public bool? IsSearch { get; set; }
    }
}
