 // This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
 // <auto-generated/> 
using System;
using System.Collections.Generic;
using System.Text;

namespace MyProject.Data.Excel.Dtos
{
    public class ReadFromExcelDto<ResultDto>
    {
        /// <summary>
        /// Return code:
        ///     200 : OK
        ///     1   : File not found
        ///     2   : Sheet not found
        ///     3   : Cant read data
        /// </summary>
        public int ResultCode { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string ErrorMessage { get; set; }

        public List<ResultDto> ListResult { get; set; }

        public List<List<string>> ListErrorRow { get; set; }
        public List<int> ListErrorRowIndex { get; set; }

        public ReadFromExcelDto()
        {
            ResultCode = 200;
            ErrorMessage = "";

            ListResult = new List<ResultDto>();
            ListErrorRow = new List<List<string>>();
            ListErrorRowIndex = new List<int>();
        }
    }
}
