// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using System;
using System.Collections.Generic;
using System.Text;

namespace MyProject.Global
{
    public class GlobalConst
    {
        public enum TrangThaiThucThiQueryConst
        {
            ThanhCong = 1,
            ThatBai,
        }

        public enum TrangThaiHieuLucConst
        {
            KhoiTao,
            HieuLuc,
            HetHieuLuc,
        }

        public enum TrangThaiDuyetConst
        {
            KhoiTao,
            ChoDuyet,
            DaDuyet,
            KhongDuyet,
        }

        public enum ReadExcelResultCodeConst
        {
            FileNotFound = 404,
            CantReadData = 500,
            OK = 200,
        }


        public enum TinhTrangMaSuDungTaiSanConst
        {
            RFID = 1,
            Barcode,
            QRCode,
        }

        public enum TrangThaiTaiSanConst
        {
            KhoiTao,
            CapPhat,
            DieuChuyen,
            ThuHoi,
            TaiSanDangSuDung,
            TaiSanSuaChua,
            TaiSanBaoDuong,
            TaiSanMat,
            TaiSanHong,
            TaiSanThanhLy,
            TaiSanHuy,
        }

        public enum TrangThaiSuaChuaBaoDuongConst
        {
            DangThucHien = 1,
            ThanhCong,
            KhongThanhCong,
        }

        public enum TrangThaiKiemKeConst
        {
            ChuaBatDau,
            DangKiemKe,
            DaKetThuc,
        }

        public enum KetQuaKiemKeTaiSanConst
        {
            KhongTimThay,
            TimThay,
            TaiSanLa,
            TaiSanLaDaThemVaoTaiSan,
        }

        public enum ViTriAntennaConst
        {
            Trong = 1,
            Ngoai,
        }

        public enum TrangThaiDuTruMuaSamConst
        {
            KhoiTao,
            HoanThanh,
            HuyBo,
        }

        public enum LoaiTaiSanConst
        {
            DiDong = 1,
            CoDinh,
        }

        public enum PhanLoaiTaiSanTrongHeThongConst
        {
            TSTrongHeThong = 1,
            TSLa,
        }

        public enum ChieuTaiSanDiChuyenConst
        {
            Ra = 1,
            Vao,
        }

        public enum CanhBaoThongBao
        {
            CapPhat = 1,
            Dieuchuyen = 2,
            ThuHoi = 3,
            BaoMat = 7,
            BaoHong = 8,
            ThanhLy = 9,
            Huy = 10,
            BatDau = 12,
            KetThuc = 13,
            SuaXong = 14,
            KhongSuaDuoc = 15,
            PhatHienVao = 16,
            PhatHienRa = 17,
        }
    }
}
