// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using System;
using System.Collections.Generic;
using System.Text;

namespace MyProject.Global
{
    public class GlobalModel
    {
        // Trạng thái thực thi query
        public static SortedList<int, string> TrangThaiThucThiQuerySorted = new SortedList<int, string>
        {
            { 1, "Thành công" },
            { 2, "Thất bại"},
        };

        // Trạng thái Hiệu lực
        public static SortedList<int, string> TrangThaiHieuLucSorted = new SortedList<int, string>
        {
            { 0, "Khởi tạo" },
            { 1, "Hiệu lực"},
            { 2, "Hết hiệu lực"},
        };

        // Trạng thái duyệt
        public static SortedList<int, string> TrangThaiDuyetSorted = new SortedList<int, string>
        {
            { 0, "Khởi tạo" },
            { 1, "Chờ duyệt"},
            { 2, "Đã duyệt"},
            { 3, "Không duyệt"},
        };

        // Trạng thái đọc Excel
        public static SortedList<int, string> ReadExcelResultCodeSorted = new SortedList<int, string>
        {
            { 404   , "Có lỗi: Không tìm thấy file!" },
            { 500   , "Không đọc được dữ liệu, sai cấu trúc file hoặc dữ liệu rỗng!" },
            { 200 , "Thành công!" }
        };

        // Trạng thái sử dụng mã của tài sản
        public static SortedList<int, string> TinhTrangMaSuDungTaiSanSorted = new SortedList<int, string>
        {
            {1, "RFID" },
            { 2, "Barcode" },
            { 3, "QR Code" },
        };

        // Trạng thái sử dụng mã của tài sản StringToInt
        public static SortedList<string, int> TinhTrangMaSuDungTaiSanSortedStringToInt = new SortedList<string, int>
        {
            {"RFID",1 },
            {"Barcode",2 },
            {"QR Code",3 },
        };

        // Trạng thái hiện tại của tài sản
        public static SortedList<int, string> TrangThaiTaiSanSorted = new SortedList<int, string>
        {
            { 0, "Khởi tạo" },
            { 1, "Cấp phát" },
            { 2, "Điều chuyển" },
            { 3, "Thu hồi" },
            { 4, "Đang sử dụng" },
            { 5, "Sửa chữa" },
            { 6, "Bảo dưỡng" },
            { 7, "Mất" },
            { 8, "Hỏng" },
            { 9, "Thanh lý" },
            { 10, "Hủy" },
        };

        public static SortedList<int, string> TrangThaiTaiSanSortedsss = new SortedList<int, string>
        {
            { 0, "Khởi tạo" },
            { 1, "Cấp phát" },
            { 2, "Điều chuyển" },
            { 3, "Thu hồi" },
            { 4, "Đang sử dụng" },
            { 5, "Sửa chữa" },
            { 6, "Bảo dưỡng" },
            { 7, "Mất" },
            { 8, "Hỏng" },
            { 9, "Thanh lý" },
            { 10, "Hủy" },
            { 11, "Dự trù mua sắm" },
        };

        public static SortedList<int, string> TrangThaiTaiSanHienThiSorted = new SortedList<int, string>
        {
            { 0, "Chưa sử dụng" },
            { 1, "Chưa sử dụng" },
            { 2, "Chưa sử dụng" },
            { 3, "Chưa sử dụng" },
            { 4, "Đang sử dụng" },
            { 5, "Sửa chữa/Bảo dưỡng" },
            { 6, "Sửa chữa/Bảo dưỡng" },
            { 7, "Mất" },
            { 8, "Hỏng" },
            { 9, "Thanh lý" },
            { 10, "Hủy" },
        };

        public static SortedList<int, string> TrangThaiTaiSanTimKiemSorted = new SortedList<int, string>
        {
            { 3, "Chưa sử dụng" },
            { 4, "Đang sử dụng" },
            { 5, "Sửa chữa/Bảo dưỡng" },
            { 7, "Mất" },
            { 8, "Hỏng" },
            { 9, "Thanh lý" },
            { 10, "Hủy" },
        };

        // Trạng thái sửa chữa,bảo dưỡng
        public static SortedList<int, string> TrangThaiSuaChuaBaoDuongSorted = new SortedList<int, string>
        {
            { 1, "Đang thực hiện" },
            { 2, "Thành công" },
            { 3, "Không thành công" },
        };

        // Trạng thái của đợt kiểm kê
        public static SortedList<int, string> TrangThaiKiemKeSorted = new SortedList<int, string>
        {
            { 0, "Chưa bắt đầu" },
            { 1, "Đang kiểm kê" },
            { 2, "Đã kết thúc" },
        };

        // Kết quả từng tài sản kiểm kê
        public static SortedList<int, string> KetQuaKiemKeTaiSanSorted = new SortedList<int, string>
        {
            { 0, "Không tìm thấy" },
            { 1, "Tìm thấy" },
            { 2, "Không thuộc danh sách" },
            { 3, "Đã thêm vào danh sách" },
        };

        // Vị trí lắp antenna
        public static SortedList<int, string> ViTriAntennaSorted = new SortedList<int, string>
        {
            { 1, "Trong" },
            { 2, "Ngoài" },
        };

        // Trạng thái phiếu dự trù mua sắm
        public static SortedList<int, string> LoaiTaiSanSorted = new SortedList<int, string>
        {
            { 1, "Đầu đọc thẻ RFID" },
            { 2, "Đầu đọc cố định" },
        };

        // Phân loại tài sản trong hệ thống
        public static SortedList<int, string> PhanLoaiTaiSanTrongHeThongSorted = new SortedList<int, string>
        {
            { 1, "Tài sản trong hệ thống" },
            { 2, "Tài sản ngoài hệ thống" },
        };

        // Chiều di chuyển của tài sản
        public static SortedList<int, string> ChieuTaiSanDiChuyenSorted = new SortedList<int, string>
        {
            { 1, "Ra" },
            { 2, "Vào" },
        };

        public static SortedList<int, string> ListLuaChonGuiMail = new SortedList<int, string>
        {
            { 1, "CapPhat" },
            { 2, "ThuHoi" },
            { 3, "DieuChuyen" },
            { 4, "BaoMat" },
            { 5, "BaoHong" },
            { 6, "ThanhLy" },
            { 7, "SuaChuaBaoDuong" },
            { 8, "BatDauKiemKe" },
            { 9, "KetThucKiemKe" },
            { 10, "HoanThanhPhieuDuTruMuaSam" },
            { 11, "HuyBoPhieuDuTruMuaSam" },
        };

        public static SortedList<int, string> LoaiCanhBaoSorted = new SortedList<int, string>
        {
            { 1, "Cấp phát" },
            { 2, "Điều chuyển" },
            { 3, "Thu hồi" },
            { 7, "Báo mất" },
            { 8, "Báo hỏng" },
            { 9, "Thanh lý" },
            { 10, "Huỷ" },
            { 12, "Bắt đầu(Đợt kiểm kê)" },
            { 13, "Kết thúc(Đợt kiểm kê)" },
            { 14, "Sửa chữa(Hoàn thành)" },
            { 15, "Sửa chữa(Không sửa được)" },
            { 16, "Tài sản vào" },
            { 17, "Tài sản ra" },
        };
        public static SortedList<string, int> trangThaiLists = new SortedList<string, int>
        {
            { "Khởi tạo", 0 },
            { "Cấp phát", 1 },
            { "Điều chuyển", 2 },
            { "Thu hồi", 3 },
            { "Đang sử dụng", 4 },
            { "Sửa chữa", 5 },
            {"Bảo dưỡng", 6 },
            { "Mất", 7 },
            { "Hỏng", 8 },
            { "Thanh lý", 9 },
            { "Hủy", 10 },
        };

        public static SortedList<string, int> tinhTrangLists = new SortedList<string, int>
        {
            { "Không thuộc danh sách", 2 },
            { "Đã thêm vào danh sách", 3 },
        };

        public static SortedList<bool?, string> TrangThaiSuDung = new SortedList<bool?, string>
        {
            { true, "Đang sử dụng" },
            { false, "Không sử dụng" },
        };

        public static SortedList<int, string> TrangThaiPhieuDuTru = new SortedList<int, string>
        {
            { 0, "Khởi tạo" },
            { 1, "Hoàn thành" },
            { 2, "Hủy bỏ" },
        };

        public static SortedList<int, string> TenBaoCaoSorted = new SortedList<int, string>
        {
            { 0, "Báo cáo người dùng" },
            { 1, "Báo cáo cảnh báo"},
            { 2, "Báo cáo thông tin thiết bị RFID"},
            { 3, "Báo cáo thông tin tài sản"},
        };

        public static SortedList<int, string> LapLaiSorted = new SortedList<int, string>
        {
            { 0, "Ngày" },
            { 1, "Tuần"},
            { 2, "Tháng"},
            { 3, "Quý"},
            { 4, "Năm"},
        };

        public static SortedList<int, string> ThuSorted = new SortedList<int, string>
        {
            { 0, "Chủ nhật" },
            { 1, "Thứ 2" },
            { 2, "Thứ 3" },
            { 3, "Thứ 4" },
            { 4, "Thứ 5" },
            { 5, "Thứ 6" },
            { 6, "Thứ 7" },
        };

        public static SortedList<int, string> QuySorted = new SortedList<int, string>
        {
            { 0, "Quý 1" },
            { 1, "Quý 2" },
            { 2, "Quý 3" },
            { 3, "Quý 4" },
        };

        public static SortedList<int, string> NgaySorted = new SortedList<int, string>
        {
            { 1, "Ngày 01" },
            { 2, "Ngày 02" },
            { 3, "Ngày 03" },
            { 4, "Ngày 04" },
            { 5, "Ngày 05" },
            { 6, "Ngày 06" },
            { 7, "Ngày 07" },
            { 8, "Ngày 08" },
            { 9, "Ngày 09" },
            { 10, "Ngày 10" },
            { 11, "Ngày 11" },
            { 12, "Ngày 12" },
            { 13, "Ngày 13" },
            { 14, "Ngày 14" },
            { 15, "Ngày 15" },
            { 16, "Ngày 16" },
            { 17, "Ngày 17" },
            { 18, "Ngày 18" },
            { 19, "Ngày 19" },
            { 20, "Ngày 20" },
            { 21, "Ngày 21" },
            { 22, "Ngày 22" },
            { 23, "Ngày 23" },
            { 24, "Ngày 24" },
            { 25, "Ngày 25" },
            { 26, "Ngày 26" },
            { 27, "Ngày 27" },
            { 28, "Ngày 28" },
            { 29, "Ngày 29" },
            { 30, "Ngày 30" },
            { 31, "Ngày 31" },
        };

        public static SortedList<int, string> NguonKinhPhiSorted = new SortedList<int, string>
        {
            { 1, "Quỹ phát triển khoa học công nghệ" },
            { 2, "Sản xuất kinh doanh" },
            { 3, "Đầu tư" },
        };
    }
}
