// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using Microsoft.EntityFrameworkCore;
using Abp.Zero.EntityFrameworkCore;
using MyProject.Authorization.Roles;
using MyProject.Authorization.Users;
using MyProject.MultiTenancy;
using MyProject.DanhMuc.Demo;
using DbEntities;

namespace MyProject.EntityFrameworkCore
{
    public class MyProjectDbContext : AbpZeroDbContext<Tenant, Role, User, MyProjectDbContext>
    {
        /* Define a DbSet for each entity of the application */
        public DbSet<Demo_File> Demo_File { get; set; }
        public DbSet<Demo> Demo { get; set; }
        public DbSet<NhaCungCap_File> NhaCungCap_File { get; set; }
        public DbSet<NhaCungCap> NhaCungCap { get; set; }
        public DbSet<LinhVucKinhDoanh> LinhVucKinhDoanh { get; set; }
        public DbSet<KiemKe_KetQuaKiemKe> KiemKe_KetQuaKiemKe { get; set; }
        public DbSet<KiemKeTaiSan> KiemKeTaiSan { get; set; }
        public DbSet<LichSuRaVaoAngten> LichSuRaVaoAngten { get; set; }
        public DbSet<LoaiTaiSan> LoaiTaiSan { get; set; }
        public DbSet<MailServer> MailServer { get; set; }
        public DbSet<PhieuTaiSan> PhieuTaiSan { get; set; }
        public DbSet<PhieuTaiSanChiTiet> PhieuTaiSanChiTiet { get; set; }
        public DbSet<QuanHuyen> QuanHuyen { get; set; }
        public DbSet<TaiSan> TaiSan { get; set; }
        public DbSet<TaiSanDinhKemFile> TaiSanDinhKemFile { get; set; }
        public DbSet<TinhThanh> TinhThanh { get; set; }
        public DbSet<ToChuc> ToChuc { get; set; }
        public DbSet<ViTriDiaLy> ViTriDiaLy { get; set; }
        public DbSet<PhieuDuTruMuaSam> PhieuDuTruMuaSam { get; set; }
        public DbSet<PhieuDuTruMuaSamChiTiet> PhieuDuTruMuaSamChiTiet { get; set; }
        public DbSet<PhieuDuTruMuaSamDinhKemFile> PhieuDuTruMuaSamDinhKemFile { get; set; }
        public DbSet<KiemKe_DoiKiemKe> KiemKe_DoiKiemKe { get; set; }
        public DbSet<CanhBao> CanhBao { get; set; }
        public DbSet<DatLichXuatBaoCao> DatLichXuatBaoCao { get; set; }

        //View - Readonly
        public DbSet<ViewTaiSan> ViewTaiSan { get; set; }
        public DbSet<ViewTaiSanSuaChuaBaoDuong> ViewTaiSanSuaChuaBaoDuong { get; set; }
        public DbSet<ViewPhieuTaiSanChiTiet> ViewPhieuTaiSanChiTiet { get; set; }
        public DbSet<ViewTaiSanMat> ViewTaiSanMat { get; set; }
        public DbSet<ViewTaiSanHong> ViewTaiSanHong { get; set; }
        public DbSet<ViewTaiSanThanhLy> ViewTaiSanThanhLy { get; set; }
        public DbSet<ViewTaiSanHuy> ViewTaiSanHuy { get; set; }
        public DbSet<ViewKhaiBaoHongMat> ViewKhaiBaoHongMat { get; set; }
        public DbSet<ViewKhaiBaoHongMatChiTiet> ViewKhaiBaoHongMatChiTiet { get; set; }
        public MyProjectDbContext(DbContextOptions<MyProjectDbContext> options)
            : base(options)
        {
        }
    }
}
