// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis
// <auto-generated/>
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace DbEntities
{
    [Table("CanhBao")]
    public class CanhBao : FullAuditedEntity, IMayHaveTenant
    {
        public virtual int? TenantId { get; set; }
        public virtual int? NguoiNhanId { get; set; }
        public virtual int? PhongBanNhanId { get; set; }
        public virtual string NoiDung { get; set; }
        public virtual int? TaiKhoanId { get; set; }
        public virtual bool? TrangThai { get; set; }
        public virtual int? PhanLoai { get; set; }
        public virtual long? LichSuRaVaoDaGuiId { get; set; }
        public virtual bool? IsCheckBaoCao { get; set; }
    }
}
