// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis
// <auto-generated/>
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace DbEntities
{
    [Table("DatLichXuatBaoCao")]
    public class DatLichXuatBaoCao : FullAuditedEntity, IMayHaveTenant
    {
        public virtual int? TenantId { get; set; }
        public virtual int? BaoCaoId { get; set; }
        public virtual int? LapLaiId { get; set; }
        public virtual int? NgayGuiBaoCaoTheoThang { get; set; }
        public virtual int? NgayGuiBaoCaoTheoTuan { get; set; }
        public virtual string NgayGuiBaoCaoTheoNam { get; set; }
        public virtual DateTime? GioGuiBaoCao { get; set; }
        public virtual int? ToChucNhanBaoCaoId { get; set; }
        public virtual string NguoiNhanBaoCaoId { get; set; }
        public virtual string GhiChu { get; set; }
    }
}
