// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;
using DbEntities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace MyProject.DanhMuc.Demo
{
     [Table("Demo")]
     public class Demo : FullAuditedEntity, IMayHaveTenant
     {
          public int? TenantId { get; set; }

          public virtual string Ma { get; set; }
          public virtual string Ten { get; set; }
          public virtual string Checkbox { get; set; }
          public virtual bool? CheckboxTrueFalse { get; set; }
          public virtual int? RadioButton { get; set; }
          public virtual bool? InputSwitch { get; set; }
          public virtual string InputMask { get; set; }
          public virtual int? Slider { get; set; }
          public virtual string Description { get; set; }
          public virtual string InputTextarea { get; set; }
          public virtual int? IntegerOnly { get; set; }
          public virtual double? Decimal { get; set; }
          public virtual DateTime? DateBasic { get; set; }
          public virtual DateTime? DateTime { get; set; }
          public virtual DateTime? DateDisable { get; set; }
          public virtual DateTime? DateMinMax { get; set; }
          public virtual DateTime? DateFrom { get; set; }
          public virtual DateTime? DateTo { get; set; }
          public virtual string DateMultiple { get; set; }
          public virtual DateTime? DateMultipleMonth { get; set; }
          public virtual DateTime? MonthOnly { get; set; }
          public virtual string TimeOnly { get; set; }
          public virtual int? AutoCompleteSingle { get; set; }
          public virtual string AutoCompleteMultiple { get; set; }
          public virtual int? DropdownSingle { get; set; }
          public virtual string DropdownMultiple { get; set; }
          public virtual ICollection<Demo_File> ListDemoFile { get; set; }
     }
}
