// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis
// <auto-generated/>
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace DbEntities
{
    [Table("KiemKe_DoiKiemKe")]
    public class KiemKe_DoiKiemKe : FullAuditedEntity<long>, IMayHaveTenant
    {
        public virtual int? TenantId { get; set; }
        public virtual long? KiemKeTaiSanId { get; set; }
        public virtual long? NguoiKiemKeId { get; set; }
        public virtual string GhiChu { get; set; }
    }
}
