// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis
// <auto-generated/>
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace DbEntities
{
    [Table("LoaiTaiSan")]
    public class LoaiTaiSan : FullAuditedEntity, IMayHaveTenant
    {
        public virtual int? TenantId { get; set; }
        public virtual int? TaiSanChaId { get; set; }
        public virtual string Ma { get; set; }
        public virtual string Ten { get; set; }
        public virtual string GhiChu { get; set; }
    }
}
