// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis
// <auto-generated/>
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace DbEntities
{
    [Table("MailServer")]
    public class MailServer : FullAuditedEntity, IMayHaveTenant
    {
        public virtual int? TenantId { get; set; }
        public virtual string Email { get; set; }
        public virtual string Password { get; set; }
        public virtual string Host { get; set; }
        public virtual string Port { get; set; }
        public virtual bool CapPhat { get; set; }
        public virtual bool ThuHoi { get; set; }
        public virtual bool DieuChuyen { get; set; }
        public virtual bool BaoMat { get; set; }
        public virtual bool BaoHong { get; set; }
        public virtual bool ThanhLy { get; set; }
        public virtual bool SuaChuaBaoDuong { get; set; }
        public virtual bool BatDauKiemKe { get; set; }
        public virtual bool KetThucKiemKe { get; set; }
        public virtual bool HoanThanhPhieuDuTruMuaSam { get; set; }
        public virtual bool HuyBoPhieuDuTruMuaSam { get; set; }
        public virtual string GhiChu { get; set; }
    }
}
