// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis
// <auto-generated/>
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DbEntities
{
    [Table("NhaCungCap")]
    public class NhaCungCap : FullAuditedEntity, IMayHaveTenant
    {
        public virtual int? TenantId { get; set; }
        public virtual string MaNhaCungCap { get; set; }
        public virtual string TenNhaCungCap { get; set; }
        public virtual string DiaChi { get; set; }
        public virtual string SoDienThoai { get; set; }
        public virtual string MaSoThue { get; set; }
        public virtual int? LinhVucKinhDoanhId { get; set; }
        public virtual string Email { get; set; }
        public virtual string GhiChu { get; set; }
        public virtual ICollection<NhaCungCap_File> NhaCungCapDinhKemFileList { get; set; }
    }
}
