// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis
// <auto-generated/>
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace DbEntities
{
    [Table("PhieuTaiSan")]
    public class PhieuTaiSan : FullAuditedEntity<long>, IMayHaveTenant
    {
        public virtual int? TenantId { get; set; }
        public virtual int? PhanLoaiId { get; set; }
        public virtual DateTime? NgayKhaiBao { get; set; }
        public virtual long? NguoiKhaiBaoId { get; set; }
        public virtual int? ToChucKhaiBaoId { get; set; }
        public virtual int? ToChucDuocNhanId { get; set; }
        public virtual string DiaChi { get; set; }
        public virtual string NoiDung { get; set; }
        public virtual string GhiChu { get; set; }
        public virtual ICollection<PhieuTaiSanChiTiet> PhieuTaiSanChiTietList { get; set; }
    }

    [Table("vKhaiBaoHongMat")]
    public class ViewKhaiBaoHongMat : FullAuditedEntity<long>
    {
        public virtual string PhongBanKhaiBao { get; set; }
        public virtual int? PhongBanKhaiBaoId { get; set; }
        public virtual string NguoiKhaiBao { get; set; }
        public virtual long? NguoiKhaiBaoId { get; set; }
        public virtual DateTime? NgayKhaiBao { get; set; }
        public virtual string NoiDungKhaiBao { get; set; }
        public virtual int? KhaiBao { get; set; }
    }

    [Table("vKhaiBaoHongMatChiTiet")]
    public class ViewKhaiBaoHongMatChiTiet : FullAuditedEntity<long>
    {
        public virtual string PhongBanKhaiBao { get; set; }
        public virtual int? PhongBanKhaiBaoId { get; set; }
        public virtual string NguoiKhaiBao { get; set; }
        public virtual long? NguoiKhaiBaoId { get; set; }
        public virtual DateTime? NgayKhaiBao { get; set; }
        public virtual string NoiDungKhaiBao { get; set; }
        public virtual int? KhaiBao { get; set; }
        public virtual long? PhieuTaiSanId { get; set; }
        public virtual int? TaiSanId { get; set; }
        public virtual int? TrangThaiId { get; set; }
        public virtual int? ViTriLapDat { get; set; }
        public virtual string GhiChu { get; set; }
        public virtual string TenTaiSan { get; set; }
        public virtual int? LoaiTaiSanId { get; set; }
        public virtual string LoaiTaiSan { get; set; }
        public virtual string SerialNumber { get; set; }
        public virtual int? NhaCungCapId { get; set; }
        public virtual string NhaCungCap { get; set; }
        public virtual DateTime? NgayMua { get; set; }
        public virtual double? NguyenGia { get; set; }
        public virtual int? PhongBanQuanLyId { get; set; }
        public virtual string PhongBanQuanLy { get; set; }
    }
}
