// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis
// <auto-generated/>
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace DbEntities
{
    [Table("PhieuDuTruMuaSamChiTiet")]
    public class PhieuDuTruMuaSamChiTiet : FullAuditedEntity<long>, IMayHaveTenant
    {
        public virtual int? TenantId { get; set; }
        public virtual long? PhieuDuTruMuaSamId { get; set; }
        public virtual string TenTaiSan { get; set; }
        public virtual string ProductNumber { get; set; }
        public virtual string HangSanXuat { get; set; }
        public virtual string NhaCungCap { get; set; }
        public virtual int? SoLuong { get; set; }
        public virtual double? DonGia { get; set; }
        public virtual string GhiChu { get; set; }
    }
}
