// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis
// <auto-generated/>
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DbEntities
{
    [Table("PhieuDuTruMuaSam")]
    public class PhieuDuTruMuaSam : FullAuditedEntity<long>, IMayHaveTenant
    {
        public virtual int? TenantId { get; set; }
        public virtual string MaPhieu { get; set; }
        public virtual string TenPhieu { get; set; }
        public virtual int? ToChucId { get; set; }
        public virtual long? NguoiLapPhieuId { get; set; }
        public virtual int? TrangThaiId { get; set; }
        public virtual string GhiChu { get; set; }
        public virtual string NgayLapPhieuStr { get; set; }
        public virtual ICollection<PhieuDuTruMuaSamChiTiet> PhieuDuTruMuaSamChiTietList { get; set; }
        public virtual ICollection<PhieuDuTruMuaSamDinhKemFile> PhieuDuTruMuaSamDinhKemFile { get; set; }
    }
}
