// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis
// <auto-generated/>
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace DbEntities
{
    [Table("QuanHuyen")]
    public class QuanHuyen : FullAuditedEntity, IMayHaveTenant
    {
        public virtual int? TenantId { get; set; }
        public virtual int? TinhThanhId { get; set; }
        public virtual string MaQuanHuyen { get; set; }
        public virtual string TenQuanHuyen { get; set; }
        public virtual string GhiChu { get; set; }
    }
}
