// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis
// <auto-generated/>
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace DbEntities
{
    [Table("TinhThanh")]
    public class TinhThanh : FullAuditedEntity, IMayHaveTenant
    {
        public virtual int? TenantId { get; set; }
        public virtual string MaTinhThanh { get; set; }
        public virtual string TenTinhThanh { get; set; }
        public virtual string GhiChu { get; set; }
    }
}
