// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis
// <auto-generated/>
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace DbEntities
{
    [Table("ToChuc")]
    public class ToChuc : FullAuditedEntity, IMayHaveTenant
    {
        public virtual int? TenantId { get; set; }
        public virtual string MaToChuc { get; set; }
        public virtual string TenToChuc { get; set; }
        public virtual int? TrucThuocToChucId { get; set; }
        public virtual int? ViTriDiaLyId { get; set; }
        public virtual string MaHexa { get; set; }
        public virtual string GhiChu { get; set; }
    }
}
