// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis
// <auto-generated/>
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace DbEntities
{
    [Table("ViTriDiaLy")]
    public class ViTriDiaLy : FullAuditedEntity, IMayHaveTenant
    {
        public virtual int? TenantId { get; set; }
        public virtual string TenViTri { get; set; }
        public virtual string DiaChi { get; set; }
        public virtual int? QuanHuyenId { get; set; }
        public virtual string GhiChu { get; set; }
    }
}
