// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
using Abp.Authorization;
using Abp.Localization;
using Abp.MultiTenancy;

namespace MyProject.Authorization
{
    public class MyProjectAuthorizationProvider : AuthorizationProvider
    {
        public override void SetPermissions(IPermissionDefinitionContext context)
        {
            context.CreatePermission(PermissionNames.Pages_Users, L("Users"));
            context.CreatePermission(PermissionNames.Pages_Roles, L("Roles"));
            context.CreatePermission(PermissionNames.Pages_Tenants, L("Tenants"), multiTenancySides: MultiTenancySides.Host);
            context.CreatePermission(PermissionNames.Pages_BaoCaoNguoiDung, L("BaoCaoNguoiDung"));
            context.CreatePermission(PermissionNames.Pages_DatLichXuatBaoCao, L("DatLichXuatBaoCao"));
            context.CreatePermission(PermissionNames.Pages_BaoCaoCanhBao, L("BaoCaoCanhBao"));
            context.CreatePermission(PermissionNames.Pages_BaoCaoThongTinThietBiRFID, L("BaoCaoThongTinThietBiRFID"));
            context.CreatePermission(PermissionNames.Pages_BaoCaoThongTinTaiSan, L("BaoCaoThongTinTaiSan"));
            context.CreatePermission(PermissionNames.Pages_QuanLyPhongBan, L("QuanLyPhongBan"));
            context.CreatePermission(PermissionNames.Pages_QuanLyDauDocCoDinh, L("QuanLyDauDocCoDinh"));
            context.CreatePermission(PermissionNames.Pages_QuanLyDauDocDiDong, L("QuanLyDauDocDiDong"));
            context.CreatePermission(PermissionNames.Pages_QuanLyLoaiTaiSan, L("QuanLyLoaiTaiSan"));
            context.CreatePermission(PermissionNames.Pages_QuanLyTaiSan, L("QuanLyTaiSanPhongBan"));
            context.CreatePermission(PermissionNames.Pages_QuanLyTaiSanTong, L("QuanLyTaiSanTong"));
            context.CreatePermission(PermissionNames.Pages_QuanLyNhaCungCap, L("QuanLyNhaCungCap"));
            context.CreatePermission(PermissionNames.Pages_QuanLyViTriDiaLy, L("QuanLyViTriDiaLy"));
            context.CreatePermission(PermissionNames.Pages_QuanLyKiemKeTaiSan, L("QuanLyKiemKeTaiSan"));
            context.CreatePermission(PermissionNames.Pages_QuanLyDuTruMuaSam, L("QuanLyDuTruMuaSam"));
            context.CreatePermission(PermissionNames.Pages_QuanLyCanhBao, L("QuanLyCanhBao"));
            context.CreatePermission(PermissionNames.Pages_QuanLyMailServer, L("QuanLyMailServer"));
            context.CreatePermission(PermissionNames.Pages_QuanLyLichSuNguoiDung, L("QuanLyLichSuNguoiDung"));
            context.CreatePermission(PermissionNames.Pages_GiamSatTaiSan, L("GiamSatTaiSan"));
            context.CreatePermission(PermissionNames.Pages_TheoDoiKetNoiThietBi, L("TheoDoiKetNoiThietBi"));
        }

        private static ILocalizableString L(string name)
        {
            return new LocalizableString(name, MyProjectConsts.LocalizationSourceName);
        }
    }
}
