// This file is not generated, but this comment is necessary to exclude it from StyleCop analysis 
// <auto-generated/> 
namespace MyProject.Authorization
{
    public static class PermissionNames
    {
        public const string Pages_Tenants = "Pages.Tenants";
        public const string Pages_Users = "Pages.Users";
        public const string Pages_Roles = "Pages.Roles";
        public const string Pages_BaoCaoNguoiDung = "Pages.BaoCaoNguoiDung";
        public const string Pages_DatLichXuatBaoCao = "Pages.DatLichXuatBaoCao";
        public const string Pages_BaoCaoCanhBao = "Pages.BaoCaoCanhBao";
        public const string Pages_BaoCaoThongTinThietBiRFID = "Pages.BaoCaoThongTinThietBiRFID";
        public const string Pages_BaoCaoThongTinTaiSan = "Pages.BaoCaoThongTinTaiSan";
        public const string Pages_QuanLyPhongBan = "Pages.QuanLyPhongBan";
        public const string Pages_QuanLyDauDocCoDinh = "Pages.QuanLyDauDocCoDinh";
        public const string Pages_QuanLyDauDocDiDong = "Pages.QuanLyDauDocDiDong";
        public const string Pages_QuanLyLoaiTaiSan = "Pages.QuanLyLoaiTaiSan";
        public const string Pages_QuanLyTaiSan = "Pages.QuanLyTaiSan";
        public const string Pages_QuanLyTaiSanTong = "Pages.QuanLyTaiSanTong";
        public const string Pages_QuanLyNhaCungCap = "Pages.QuanLyNhaCungCap";
        public const string Pages_QuanLyViTriDiaLy = "Pages.QuanLyViTriDiaLy";
        public const string Pages_QuanLyKiemKeTaiSan = "Pages.QuanLyKiemKeTaiSan";
        public const string Pages_QuanLyDuTruMuaSam = "Pages.QuanLyDuTruMuaSam";
        public const string Pages_QuanLyCanhBao = "Pages.QuanLyCanhBao";
        public const string Pages_QuanLyMailServer = "Pages.QuanLyMailServer";
        public const string Pages_QuanLyLichSuNguoiDung = "Pages.QuanLyLichSuNguoiDung";
        public const string Pages_GiamSatTaiSan = "Pages.GiamSatTaiSan";
        public const string Pages_TheoDoiKetNoiThietBi = "Pages.TheoDoiKetNoiThietBi";
    }
}
